# Generated by Django 6.0.4 on 2026-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='occupied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
