# Generated by Django 6.0.4 on 2026-06-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_table_is_occupied_table_occupied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
